BASE_LOG_DIR: logs
ENVIRONMENT: LOCAL

TRAINNING_LOG:
  DIRECTORY: trainning
  FILE_NAME: TRAINNING_LOG
  LEVEL: INFO

PREDICTION_LOG:
  DIRECTORY: prediction
  FILE_NAME: PREDICTION_LOG
  LEVEL: INFO
