BASE_LOG_DIR: logs
ENVIRONMENT: LOCAL

TRAINING_LOG:
  DIRECTORY: trainning
  FILE_NAME: TRAINNING_LOG
  LEVEL: INFO

PREDICTION_LOG:
  DIRECTORY: prediction
  FILE_NAME: PREDICTION_LOG
  LEVEL: INFO

DEFAULT_DATA_DIR: default_dataset
SCHEMA_DIR : config
TRAINING_SCHEMA_PATH : schema_training.json
PREDICTION_SCHEMA_PATH : schema_prediction.json
